### ISSUE TITLE
Docker recompile error after defaults change

### ISSUE THREAD

**Issue by slafeir** [MacroPower/macropower-analytics-panel#19]
Running in docker, trying to recompile the plugin after editing the defaults.json

```docker
FROM grafana/grafana:7.3.5
USER root
RUN apk update \ 
 && apk add jq \
 && apk add git \
 && apk add unzip \
 && apk add nodejs npm \
 && rm -rf /var/cache/apk/*
# download plugin
ADD https://github.com/MacroPower/macropower-analytics-panel/archive/refs/tags/v2.0.0.zip /var/lib/grafana/plugins/macropower-analytics-panel.zip
RUN unzip /var/lib/grafana/plugins/macropower-analytics-panel.zip -d /var/lib/grafana/plugins/ && rm /var/lib/grafana/plugins/macropower-analytics-panel.zip
# copy changed plugin defaults 
COPY --chown=644 defaults.json /var/lib/grafana/plugins/macropower-analytics-panel-2.0.0/src/defaults.json
# recompile plugin
RUN cd /var/lib/grafana/plugins/macropower-analytics-panel/ && npm install
RUN cd /var/lib/grafana/plugins/macropower-analytics-panel/ && npm run build
USER grafana
```
And getting a few problems

1. Not really a problem, more a concern. On npm install I get`found 6 vulnerabilities (2 low, 3 moderate, 1 high)` Any plans to fix these? 
2. Getting an error on npm run build: 
```bash
> [10/12] RUN cd /var/lib/grafana/plugins/macropower-analytics-panel-2.0.0/ && npm run build:
#15 0.619 
#15 0.619 > analytics-panel@2.0.0 build /var/lib/grafana/plugins/macropower-analytics-panel-2.0.0
#15 0.619 > grafana-toolkit plugin:build
#15 0.619 
#15 2.157   Using Node.js [object Object]
#15 3.642   Using @grafana/toolkit [object Object]
#15 3.645 - Preparing
#15 3.653 ✔ Preparing
#15 3.654 - Linting
#15 5.022   Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.
#15 5.952   
#15 5.952   
#15 5.955   
#15 5.955   /var/lib/grafana/plugins/macropower-analytics-panel-2.0.0/src/payload.ts
#15 5.955     11:11  error  Array type using 'Array<string>' is forbidden for simple types. Use 'string[]' instead  @typescript-eslint/array-type
#15 5.955   
#15 5.955   /var/lib/grafana/plugins/macropower-analytics-panel-2.0.0/src/utils.ts
#15 5.955     51:20  error  Array type using 'Array<TemplateVariable>' is forbidden for simple types. Use 'TemplateVariable[]' instead  @typescript-eslint/array-type
#15 5.955     56:16  error  Array type using 'Array<string>' is forbidden for simple types. Use 'string[]' instead                      @typescript-eslint/array-type
#15 5.955   
#15 5.955   ✖ 3 problems (3 errors, 0 warnings)
#15 5.955     3 errors and 0 warnings potentially fixable with the `--fix` option.
#15 5.955   
#15 5.955   
#15 5.955   
#15 5.957   Trace: Error: 3 linting errors found in 6 files
#15 5.957       at /var/lib/grafana/plugins/macropower-analytics-panel-2.0.0/node_modules/@grafana/toolkit/src/cli/tasks/plugin.build.js:118:31
#15 5.957       at step (/var/lib/grafana/plugins/macropower-analytics-panel-2.0.0/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:140:27)
#15 5.957       at Object.next (/var/lib/grafana/plugins/macropower-analytics-panel-2.0.0/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:121:57)
#15 5.957       at fulfilled (/var/lib/grafana/plugins/macropower-analytics-panel-2.0.0/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:111:62)
#15 5.957       at processTicksAndRejections (internal/process/task_queues.js:97:5)
#15 5.957       at /var/lib/grafana/plugins/macropower-analytics-panel-2.0.0/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:25:29
#15 5.957       at step (/var/lib/grafana/plugins/macropower-analytics-panel-2.0.0/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:140:27)
#15 5.957       at Object.throw (/var/lib/grafana/plugins/macropower-analytics-panel-2.0.0/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:121:57)
#15 5.957       at rejected (/var/lib/grafana/plugins/macropower-analytics-panel-2.0.0/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:112:69)
#15 5.957       at processTicksAndRejections (internal/process/task_queues.js:97:5)
#15 5.957 ✖ 3 linting errors found in 6 files
#15 5.992 npm ERR! code ELIFECYCLE
#15 5.992 npm ERR! errno 1
#15 5.998 npm ERR! analytics-panel@2.0.0 build: `grafana-toolkit plugin:build`
#15 5.998 npm ERR! Exit status 1
#15 5.998 npm ERR! 
#15 5.998 npm ERR! Failed at the analytics-panel@2.0.0 build script.
#15 5.998 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#15 6.005 
#15 6.005 npm ERR! A complete log of this run can be found in:
#15 6.005 npm ERR!     /root/.npm/_logs/2021-05-07T19_21_28_248Z-debug.log
------
executor failed running [/bin/sh -c cd /var/lib/grafana/plugins/macropower-analytics-panel-2.0.0/ && npm run build]: exit code: 1
```

Any help on this build error would be appreciated!

**Comment by MacroPower** [comment]
Hey @slafeir, it's pretty strange that you're getting different results from me, but those look like legitimate problems so I'm fixing them in #20 regardless of why this is.

You should be able to use that branch like so:

```
FROM grafana/grafana:7.3.5
USER root
RUN apk update \ 
    && apk add jq \
    && apk add git \
    && apk add unzip \
    && apk add nodejs npm \
    && rm -rf /var/cache/apk/*
# download plugin
ADD https://github.com/MacroPower/macropower-analytics-panel/archive/refs/heads/feature/grafana-eslint-config.zip /var/lib/grafana/plugins/macropower-analytics-panel.zip
RUN unzip /var/lib/grafana/plugins/macropower-analytics-panel.zip -d /var/lib/grafana/plugins/ && rm /var/lib/grafana/plugins/macropower-analytics-panel.zip
# copy changed plugin defaults 
COPY --chown=644 defaults.json /var/lib/grafana/plugins/macropower-analytics-panel-feature-grafana-eslint-config/src/defaults.json
# recompile plugin
RUN cd /var/lib/grafana/plugins/macropower-analytics-panel-feature-grafana-eslint-config/ && npm ci
RUN cd /var/lib/grafana/plugins/macropower-analytics-panel-feature-grafana-eslint-config/ && npm run build
USER grafana
```

Let me know if this helps.

I can't really do anything about the vulnerabilities as these are just problems with dependencies, which are basically all from Grafana.

**Comment by slafeir** [comment]
@MacroPower Thanks for the quick response! Your feature branch fixed it.

**Comment by MacroPower** [comment]
Nice. I just merged that into master. Since it's not actually changing anything I'm not going to release this on its own, but next time there's a release it should be included. @slafeir not sure if you can still pull after I delete that branch so you may want to download the zip @ a1c9aa0e40fa2cd8796be6c95334ff27d77e3a47. I'll leave it up for a few weeks just in case.
